services:
  simple-server:
    image: ahmed0427/simple-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/simpletable?sslmode=disable
      - VERSION=latest
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - private-network

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simpletable
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d simpletable"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - private-network

volumes:
  postgres-data:
    driver: local

networks:
  private-network:
    driver: bridge
